/* Proyecto Final: gomitas_sf
Alumno: Kevin Larguía
*/

CREATE DATABASE IF NOT EXISTS gomitas_sf;
USE gomitas_sf;

-- 1. Tabla de proveedores de insumos
CREATE TABLE PROVEEDORES (
    ID_PROV INT AUTO_INCREMENT PRIMARY KEY,
    NOM_DIST VARCHAR(100) NOT NULL,
    TEL_PROV VARCHAR(20)
);

-- 2. Registro de inversiones en publicidad
CREATE TABLE CAMPANAS_ADS (
    ID_ADS INT AUTO_INCREMENT PRIMARY KEY,
    NOM_ADS VARCHAR(100) NOT NULL,
    PLAT_ADS VARCHAR(30),
    COST_ADS DECIMAL(10, 2) DEFAULT 0.00
);

-- 3. Categorías generales de los productos
CREATE TABLE CATEGORIAS_PRODUCTOS (
    ID_CAT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CAT VARCHAR(50) NOT NULL
);

-- 4. Métodos de pago disponibles
CREATE TABLE METODOS_PAGO (
    ID_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    NOM_PAGO VARCHAR(50) NOT NULL
);

-- 5. Estados posibles del pedido
CREATE TABLE ESTADOS_PEDIDO (
    ID_ESTADO INT AUTO_INCREMENT PRIMARY KEY,
    DESC_ESTADO VARCHAR(50) NOT NULL
);

-- 6. Zonas de envío en Santa Fe
CREATE TABLE ZONAS_ENVIO (
    ID_ZONA INT AUTO_INCREMENT PRIMARY KEY,
    NOM_ZONA VARCHAR(50) NOT NULL,
    COSTO_ENVIO DECIMAL(10, 2) DEFAULT 0.00
);

-- 7. Personal del emprendimiento
CREATE TABLE EMPLEADOS (
    ID_EMP INT AUTO_INCREMENT PRIMARY KEY,
    NOM_EMP VARCHAR(100) NOT NULL,
    PUESTO VARCHAR(50)
);

-- 8. Datos de contacto de clientes
CREATE TABLE CLIENTES (
    ID_CLI INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CLI VARCHAR(100) NOT NULL,
    WA_CLI VARCHAR(20),
    ORIG_CLI VARCHAR(50)
);

-- 9. Insumos (Gomitas por variedad y costo)
CREATE TABLE GOMITAS (
    ID_GOM INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROV INT,
    NOM_GOM VARCHAR(50) NOT NULL,
    MAR_GOM VARCHAR(50),
    TIP_SAB ENUM('Dulce', 'Ácida') NOT NULL,
    PRC_KG DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_PROV) REFERENCES PROVEEDORES(ID_PROV)
);

-- 10. Catálogo de productos y contenedores
CREATE TABLE PRODUCTOS (
    ID_PROD INT AUTO_INCREMENT PRIMARY KEY,
    ID_CAT INT,
    NOM_CONT VARCHAR(50) NOT NULL,
    PRC_FIJO DECIMAL(10, 2) NOT NULL,
    FLG_TEMP BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_CAT) REFERENCES CATEGORIAS_PRODUCTOS(ID_CAT)
);

-- 11. Tabla principal de pedidos (Hechos)
CREATE TABLE PEDIDOS (
    ID_PED INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLI INT NOT NULL,
    ID_ADS INT,
    ID_PAGO INT,
    ID_ESTADO INT,
    ID_ZONA INT,
    ID_EMP INT,
    FCH_PED DATETIME DEFAULT CURRENT_TIMESTAMP,
    NOT_PED TEXT,
    TOT_PED DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLI),
    FOREIGN KEY (ID_ADS) REFERENCES CAMPANAS_ADS(ID_ADS),
    FOREIGN KEY (ID_PAGO) REFERENCES METODOS_PAGO(ID_PAGO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS_PEDIDO(ID_ESTADO),
    FOREIGN KEY (ID_ZONA) REFERENCES ZONAS_ENVIO(ID_ZONA),
    FOREIGN KEY (ID_EMP) REFERENCES EMPLEADOS(ID_EMP)
);

-- 12. Detalles de servicios para eventos
CREATE TABLE SERVICIOS_EVENTOS (
    ID_SERV INT AUTO_INCREMENT PRIMARY KEY,
    ID_PED INT NOT NULL,
    TIP_SERV ENUM('Candy Bar', 'Mesa Dulce') NOT NULL,
    PAQ_500 INT DEFAULT 0,
    PERS_EVT INT DEFAULT 0,
    TEMA_EVT VARCHAR(50),
    FOREIGN KEY (ID_PED) REFERENCES PEDIDOS(ID_PED)
);

-- 13. Desglose de productos por cada pedido
CREATE TABLE DETALLE_PEDIDO (
    ID_DET INT AUTO_INCREMENT PRIMARY KEY,
    ID_PED INT NOT NULL,
    ID_PROD INT NOT NULL,
    CANT INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_PED) REFERENCES PEDIDOS(ID_PED),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID_PROD)
);

-- 14. Selección personalizada de gomitas
CREATE TABLE SELECCION_GOMITAS (
    ID_SEL INT AUTO_INCREMENT PRIMARY KEY,
    ID_DET INT NOT NULL,
    ID_GOM INT NOT NULL,
    FOREIGN KEY (ID_DET) REFERENCES DETALLE_PEDIDO(ID_DET),
    FOREIGN KEY (ID_GOM) REFERENCES GOMITAS(ID_GOM)
);

-- 15. Tabla de auditoría para control de costos
CREATE TABLE AUDITORIA_PRECIOS (
    ID_AUD INT AUTO_INCREMENT PRIMARY KEY,
    ID_GOM INT,
    PRECIO_ANTERIOR DECIMAL(10,2),
    PRECIO_NUEVO DECIMAL(10,2),
    FECHA_CAMBIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO VARCHAR(50)
);
